ALTER TABLE rag_config ADD COLUMN IF NOT EXISTS embedding_api_key VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE rag_config ADD COLUMN IF NOT EXISTS embedding_base_url VARCHAR(500) NOT NULL DEFAULT '';
