ALTER TABLE token_usages ADD COLUMN IF NOT EXISTS api_path VARCHAR(100);
ALTER TABLE token_usages ADD COLUMN IF NOT EXISTS status_code INTEGER;
ALTER TABLE token_usages ADD COLUMN IF NOT EXISTS duration_ms INTEGER;
