package service

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"steel-agent-backend/internal/model"
	"steel-agent-backend/internal/repository"
	"steel-agent-backend/pkg/ai"

	"github.com/sashabaranov/go-openai"
)

// ---------------------------------------------------------------------------
// Agent Service — Planner, Executor, Reflector
//
// Implements Tasks 2, 3, and 4 from specs/evolve-to-true-agent.
// ---------------------------------------------------------------------------

// SubAgent defines the interface for a specialized agent that handles
// domain-specific tasks. Each SubAgent is responsible for executing steps
// that match its domain (e.g. price queries, quotations, tenders).
type SubAgent interface {
	Name() string
	Execute(ctx context.Context, step PlanStep, workMemory map[string]string) (*StepResult, error)
}

// AgentService orchestrates multi-step agent planning, execution, and reflection.
type AgentService struct {
	llmAdapter     *ai.LLMAdapter
	agentConfigSvc *AgentConfigService
	memoryRepo     *repository.AgentMemoryRepository
	vectorRepo     *repository.AgentMemoryVectorRepository
	subAgents      map[string]SubAgent
}

// NewAgentService creates a new AgentService with the required dependencies.
func NewAgentService(
	llmAdapter *ai.LLMAdapter,
	agentConfigSvc *AgentConfigService,
	memoryRepo *repository.AgentMemoryRepository,
	vectorRepo *repository.AgentMemoryVectorRepository,
) *AgentService {
	return &AgentService{
		llmAdapter:     llmAdapter,
		agentConfigSvc: agentConfigSvc,
		memoryRepo:     memoryRepo,
		vectorRepo:     vectorRepo,
	}
}

// RegisterSubAgent adds a SubAgent to the AgentService's registry.
// Multiple calls with the same name will overwrite the previous registration.
func (s *AgentService) RegisterSubAgent(agent SubAgent) {
	if s.subAgents == nil {
		s.subAgents = make(map[string]SubAgent)
	}
	s.subAgents[agent.Name()] = agent
}

// RouteToSubAgent looks up a SubAgent by name. Returns the agent and true if
// found, or nil and false otherwise.
func (s *AgentService) RouteToSubAgent(step PlanStep) (SubAgent, bool) {
	if s.subAgents == nil {
		return nil, false
	}
	agent, ok := s.subAgents[step.SubAgentName]
	return agent, ok
}

// ---------------------------------------------------------------------------
// Type Definitions
// ---------------------------------------------------------------------------

// PlanStep represents a single step in an agent execution plan.
type PlanStep struct {
	Step         int                    `json:"step"`
	Intent       string                 `json:"intent"`
	ToolName     string                 `json:"tool_name"`
	Params       map[string]interface{} `json:"params,omitempty"`
	DependsOn    []int                  `json:"depends_on,omitempty"`
	SubAgentName string                 `json:"sub_agent_name,omitempty"`
}

// AgentPlan is the full execution plan generated by the Planner.
type AgentPlan struct {
	Steps     []PlanStep `json:"steps"`
	MaxSteps  int        `json:"max_steps"`
	CreatedAt time.Time  `json:"created_at"`
}

// StepResult represents the outcome of executing a single step.
type StepResult struct {
	StepIndex int    `json:"step_index"`
	Success   bool   `json:"success"`
	Result    string `json:"result"` // JSON string from tool
	Error     string `json:"error,omitempty"`
	Retries   int    `json:"retries"`
}

// ReflectionResult represents the outcome of reflecting on a step result.
type ReflectionResult struct {
	Status     string `json:"status"` // "ok", "replan", "failed"
	Reason     string `json:"reason,omitempty"`
	Suggestion string `json:"suggestion,omitempty"`
}

// AgentEvent represents a streaming event pushed to the SSE channel.
type AgentEvent struct {
	Type string      `json:"type"`
	Data interface{} `json:"data"`
}

const (
	agentPlannerPrompt = `You are an agent planner for a steel industry assistant. Given a user message, break it down into an ordered list of execution steps.

Each step must specify:
- step: step number (starting from 1)
- intent: short description of what this step does
- tool_name: from the available tools list (use empty string "" if no specific tool is needed)
- params: parameters to pass to the tool
- depends_on: (optional) list of step indices this step depends on
- sub_agent_name: (optional) the name of the specialized sub-agent to handle this step

Rules:
1. Only use tools from the provided list
2. Keep steps minimal and focused
3. If the user request is simple, use 1-2 steps
4. When the task involves a specific domain, set sub_agent_name to the appropriate agent: price/price_trend → 'price_agent', quotation → 'quotation_agent', tender → 'tender_agent', knowledge/search → 'knowledge_agent', alert/convert/weight → 'alert_agent'
5. Return ONLY valid JSON, no other text`
)

// ============================================================================
// Planner Implementation (Task 2)
// ============================================================================

// GeneratePlan analyses the user message and generates an execution plan via LLM.
// It first retrieves long-term memories for the user and injects them as context
// into the planner prompt so the agent can leverage cross-session preferences.
func (s *AgentService) GeneratePlan(
	ctx context.Context,
	userID uint,
	userMessage string,
	history []model.ChatMessage,
	availableTools []openai.Tool,
) (*AgentPlan, error) {
	cfg, cfgErr := s.agentConfigSvc.GetAgentConfig(ctx)
	maxSteps := 5
	if cfgErr == nil && cfg != nil && cfg.MaxSteps > 0 && cfg.MaxSteps <= 10 {
		maxSteps = cfg.MaxSteps
	}

	// Task 7.2: Retrieve long-term memories and build context string.
	var memoryContext string
	if s.memoryRepo != nil {
		memoryContext = s.buildMemoryContext(ctx, userID)
	}

	// Task 22: Semantic memory retrieval — search for similar past conversation
	// summaries using vector similarity before generating the plan.
	var semanticContext string
	if s.vectorRepo != nil && userMessage != "" {
		semanticContext = s.buildSemanticMemoryContext(ctx, userID, userMessage)
	}

	// Build a description of available tools for the planner prompt.
	toolDescriptions := s.buildToolListForPlanner(availableTools)

	// Build planner messages.
	systemContent := agentPlannerPrompt
	if memoryContext != "" {
		systemContent = memoryContext + "\n" + agentPlannerPrompt
	}
	if semanticContext != "" {
		systemContent = semanticContext + "\n" + systemContent
	}
	messages := []openai.ChatCompletionMessage{
		{Role: openai.ChatMessageRoleSystem, Content: systemContent},
		{
			Role:    openai.ChatMessageRoleUser,
			Content: fmt.Sprintf("Available tools:\n%s\n\nUser message: %s\n\nGenerate a JSON plan:", toolDescriptions, userMessage),
		},
	}

	// If history exists, include a summary.
	if len(history) > 0 {
		historySummary := buildHistorySummary(history)
		messages = []openai.ChatCompletionMessage{
			{Role: openai.ChatMessageRoleSystem, Content: systemContent},
			{
				Role:    openai.ChatMessageRoleUser,
				Content: fmt.Sprintf("Conversation history:\n%s\n\nAvailable tools:\n%s\n\nUser message: %s\n\nGenerate a JSON plan:", historySummary, toolDescriptions, userMessage),
			},
		}
	}

	// Call LLM (non-streaming) for the plan.
	resp, err := s.llmAdapter.Chat(ctx, messages)
	if err != nil {
		slog.Warn("planner LLM call failed, using fallback single-step plan", "error", err)
		return s.fallbackPlan(maxSteps), nil
	}

	if len(resp.Choices) == 0 || resp.Choices[0].Message.Content == "" {
		slog.Warn("planner returned empty response, using fallback single-step plan")
		return s.fallbackPlan(maxSteps), nil
	}

	raw := resp.Choices[0].Message.Content
	plan, parseErr := parsePlanJSON(raw)
	if parseErr != nil {
		slog.Warn("planner returned invalid JSON, using fallback single-step plan",
			"raw", raw,
			"error", parseErr,
		)
		return s.fallbackPlan(maxSteps), nil
	}

	// Cap steps to maxSteps.
	if len(plan.Steps) > maxSteps {
		plan.Steps = plan.Steps[:maxSteps]
	}
	plan.MaxSteps = maxSteps
	plan.CreatedAt = time.Now()

	return plan, nil
}

// buildToolListForPlanner creates a human-readable list of tools for the planner prompt.
func (s *AgentService) buildToolListForPlanner(tools []openai.Tool) string {
	if len(tools) == 0 {
		return "(no tools available)"
	}

	var parts []string
	for _, t := range tools {
		if t.Function == nil {
			continue
		}
		desc := t.Function.Description
		if desc == "" {
			desc = "(no description)"
		}
		parts = append(parts, fmt.Sprintf("- %s: %s", t.Function.Name, desc))
	}
	if len(parts) == 0 {
		return "(no tools available)"
	}
	return strings.Join(parts, "\n")
}

// parsePlanJSON attempts to parse LLM output into an AgentPlan.
func parsePlanJSON(raw string) (*AgentPlan, error) {
	raw = strings.TrimSpace(raw)

	// Strip markdown code fences if present.
	if strings.HasPrefix(raw, "```") {
		raw = strings.TrimPrefix(raw, "```json")
		raw = strings.TrimPrefix(raw, "```")
		raw = strings.TrimSuffix(raw, "```")
		raw = strings.TrimSpace(raw)
	}

	var plan AgentPlan
	if err := json.Unmarshal([]byte(raw), &plan); err != nil {
		return nil, fmt.Errorf("parse plan JSON: %w", err)
	}
	return &plan, nil
}

// fallbackPlan generates a single-step fallback plan when the LLM fails.
func (s *AgentService) fallbackPlan(maxSteps int) *AgentPlan {
	return &AgentPlan{
		Steps: []PlanStep{
			{
				Step:     1,
				Intent:   "general",
				ToolName: "",
				Params:   nil,
			},
		},
		MaxSteps:  maxSteps,
		CreatedAt: time.Now(),
	}
}

// buildHistorySummary creates a brief summary of past conversation for the planner.
func buildHistorySummary(history []model.ChatMessage) string {
	const maxHistoryEntries = 6
	start := 0
	if len(history) > maxHistoryEntries {
		start = len(history) - maxHistoryEntries
	}

	var parts []string
	for _, m := range history[start:] {
		role := m.Role
		content := m.Content
		if len(content) > 200 {
			content = content[:200] + "..."
		}
		parts = append(parts, fmt.Sprintf("[%s]: %s", role, content))
	}
	return strings.Join(parts, "\n")
}

// buildMemoryContext retrieves long-term memories for a user and formats them
// as a planner context string. Returns empty string if no memories are found.
// The keys queried align with those set by ChatService.saveMemories.
func (s *AgentService) buildMemoryContext(ctx context.Context, userID uint) string {
	memoryKeys := []string{"last_category", "last_spec", "last_region", "last_query"}
	labelMap := map[string]string{
		"last_category": "上次查询品种",
		"last_spec":     "上次查询规格",
		"last_region":   "上次查询地区",
		"last_query":    "上次查询内容",
	}

	var lines []string
	for _, key := range memoryKeys {
		memories, err := s.memoryRepo.FindByUserAndKey(ctx, userID, key)
		if err != nil || len(memories) == 0 {
			continue
		}
		value := strings.TrimSpace(memories[0].Value)
		if value == "" {
			continue
		}
		label := labelMap[key]
		lines = append(lines, fmt.Sprintf("- %s: %s", label, value))
	}

	if len(lines) == 0 {
		return ""
	}

	return "[用户历史偏好]\n" + strings.Join(lines, "\n")
}

// buildSemanticMemoryContext vectorizes the user's input, searches for similar
// past conversation summaries using pgvector cosine similarity, and formats
// the results as context for the planner prompt.
// Returns an empty string if no similar memories are found or vector search is unavailable.
func (s *AgentService) buildSemanticMemoryContext(ctx context.Context, userID uint, userMessage string) string {
	if s.llmAdapter == nil {
		return ""
	}

	// Step 1: Vectorize the user input.
	embeddings, err := s.llmAdapter.CreateEmbeddings(ctx, "text-embedding-3-small", []string{userMessage})
	if err != nil || len(embeddings) == 0 || len(embeddings[0]) == 0 {
		return ""
	}

	queryVector := float32ArrayToVector(embeddings[0])

	// Step 2: Search for similar past memories.
	memories, err := s.vectorRepo.VectorSearch(ctx, userID, queryVector, 0.75, 5)
	if err != nil || len(memories) == 0 {
		return ""
	}

	// Step 3: Format retrieved memories as context.
	var lines []string
	for _, mem := range memories {
		content := strings.TrimSpace(mem.Content)
		if content == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("- %s (相似度: %.0f%%)", content, mem.Similarity*100))
	}

	if len(lines) == 0 {
		return ""
	}

	return "[历史相关对话摘要]\n" + strings.Join(lines, "\n")
}

// ============================================================================
// Executor Implementation (Task 3)
// ============================================================================

// ExecuteStep runs a single plan step by calling the LLM with the step's
// parameters and extracting the tool invocation result.
func (s *AgentService) ExecuteStep(
	ctx context.Context,
	step PlanStep,
	workMemory map[string]string,
	tools []openai.Tool,
) (*StepResult, error) {
	// If no tool is specified, let the caller handle it directly.
	if step.ToolName == "" {
		return &StepResult{
			StepIndex: step.Step,
			Success:   true,
			Result:    "",
		}, nil
	}

	// Resolve parameters: inject any dependency outputs from workMemory.
	params := s.resolveParams(step, workMemory)

	// Build messages for the tool execution.
	systemMsg := openai.ChatCompletionMessage{
		Role:    openai.ChatMessageRoleSystem,
		Content: fmt.Sprintf("You are a steel industry assistant. Execute the tool %q with the given parameters. Always call the tool to get real data.", step.ToolName),
	}

	paramsJSON, _ := json.Marshal(params)
	userMsg := openai.ChatCompletionMessage{
		Role:    openai.ChatMessageRoleUser,
		Content: fmt.Sprintf("Step intent: %s\nTool: %s\nParams: %s", step.Intent, step.ToolName, string(paramsJSON)),
	}

	messages := []openai.ChatCompletionMessage{systemMsg, userMsg}

	// Call LLM with tools.
	resp, err := s.llmAdapter.ChatWithTools(ctx, messages, tools)
	if err != nil {
		return &StepResult{
			StepIndex: step.Step,
			Success:   false,
			Error:     fmt.Sprintf("LLM call failed: %v", err),
		}, nil
	}

	if len(resp.Choices) == 0 {
		return &StepResult{
			StepIndex: step.Step,
			Success:   false,
			Error:     "LLM returned empty response",
		}, nil
	}

	choice := resp.Choices[0]

	// If the LLM returned text directly (no tool call), return it as the result.
	if choice.Message.Content != "" && len(choice.Message.ToolCalls) == 0 {
		return &StepResult{
			StepIndex: step.Step,
			Success:   true,
			Result:    choice.Message.Content,
		}, nil
	}

	// If no tool calls, this is an incomplete response.
	if len(choice.Message.ToolCalls) == 0 {
		return &StepResult{
			StepIndex: step.Step,
			Success:   true,
			Result:    "",
		}, nil
	}

	// Extract the tool call result.
	// At this point the LLM has returned a tool call request, but we haven't
	// executed the actual tool function. The ChatWithTools call returns the
	// LLM's decision to call a tool, not the tool's output.
	// We need to extract which tool was called and with what arguments.

	toolCall := choice.Message.ToolCalls[0]

	if toolCall.Function.Name == "" {
		return &StepResult{
			StepIndex: step.Step,
			Success:   true,
			Result:    choice.Message.Content,
		}, nil
	}

	// We have a tool call. Return the function name and arguments as the result
	// so the caller (who owns the tool implementations) can execute it.
	resultJSON, _ := json.Marshal(map[string]interface{}{
		"tool":      toolCall.Function.Name,
		"arguments": toolCall.Function.Arguments,
		"content":   choice.Message.Content,
	})

	return &StepResult{
		StepIndex: step.Step,
		Success:   true,
		Result:    string(resultJSON),
	}, nil
}

// resolveParams injects dependency step results from workMemory into the
// current step's parameters.
func (s *AgentService) resolveParams(step PlanStep, workMemory map[string]string) map[string]interface{} {
	params := make(map[string]interface{})
	for k, v := range step.Params {
		params[k] = v
	}

	// If no dependencies, return as-is.
	if len(step.DependsOn) == 0 {
		return params
	}

	// Inject dependency results into params.
	for _, depStep := range step.DependsOn {
		key := fmt.Sprintf("step_%d", depStep)
		value, ok := workMemory[key]
		if !ok {
			continue
		}

		// Try to parse the dependency result as JSON and merge relevant fields.
		var depResult map[string]interface{}
		if err := json.Unmarshal([]byte(value), &depResult); err != nil {
			// Not JSON, store as "previous_result".
			params["previous_result"] = value
			continue
		}

		// Merge common fields from the dependency result.
		for _, field := range []string{"category", "spec", "region", "price", "result"} {
			if v, ok := depResult[field]; ok {
				params[field] = v
			}
		}
	}

	return params
}

// ExecutePlan runs the entire plan step by step, streaming AgentEvents through
// the returned channel. The caller is responsible for converting events to
// SSE format.
func (s *AgentService) ExecutePlan(
	ctx context.Context,
	plan *AgentPlan,
	tools []openai.Tool,
) (<-chan AgentEvent, error) {
	cfg, cfgErr := s.agentConfigSvc.GetAgentConfig(ctx)
	maxRetries := 2
	if cfgErr == nil && cfg != nil && cfg.MaxRetries > 0 && cfg.MaxRetries <= 5 {
		maxRetries = cfg.MaxRetries
	}

	ch := make(chan AgentEvent, 50)

	go func() {
		defer close(ch)

		// Push plan_created event.
		ch <- AgentEvent{Type: "plan_created", Data: plan}

		workMemory := make(map[string]string)

		for i, step := range plan.Steps {
			// Push step_start event.
			ch <- AgentEvent{
				Type: "step_start",
				Data: map[string]interface{}{
					"step": step.Step,
					"tool": step.ToolName,
				},
			}

			// Route to sub-agent if step specifies one.
			var result *StepResult
			var lastErr error

			if step.SubAgentName != "" {
				if subAgent, ok := s.RouteToSubAgent(step); ok {
					result, lastErr = subAgent.Execute(ctx, step, workMemory)
					if lastErr != nil {
						slog.Warn("sub-agent execution error",
							"step", step.Step,
							"sub_agent", step.SubAgentName,
							"error", lastErr,
						)
					}
				} else {
					// Sub-agent not registered; fall through to default execution.
					slog.Warn("sub-agent not found, falling back to default execution",
						"step", step.Step,
						"sub_agent", step.SubAgentName,
					)
				}
			}

			// If no sub-agent or sub-agent not found, execute with retries.
			if result == nil {
				for retry := 0; retry <= maxRetries; retry++ {
					if retry > 0 {
						// Wait 1 second between retries.
						select {
						case <-ctx.Done():
							ch <- AgentEvent{
								Type: "step_failed",
								Data: map[string]interface{}{
									"step":  step.Step,
									"error": "cancelled",
								},
							}
							return
						case <-time.After(1 * time.Second):
						}
					}

					result, lastErr = s.ExecuteStep(ctx, step, workMemory, tools)
					if lastErr != nil {
						slog.Warn("step execution error",
							"step", step.Step,
							"retry", retry,
							"error", lastErr,
						)
						continue
					}

					if result.Success {
						break
					}
				}
			}

			if result == nil || !result.Success {
				errMsg := "unknown error"
				if result != nil {
					errMsg = result.Error
					result.Retries = maxRetries
				}
				ch <- AgentEvent{
					Type: "step_failed",
					Data: map[string]interface{}{
						"step":  step.Step,
						"error": errMsg,
					},
				}

				// Evaluate the failure.
				reflection := s.evaluateFailure(step, result)
				if reflection.Status == "failed" {
					ch <- AgentEvent{Type: "reflection", Data: reflection}
					break
				}

				if reflection.Status == "replan" {
					ch <- AgentEvent{Type: "reflection", Data: reflection}

					// Replan remaining steps.
					newPlan, replanErr := s.Replan(ctx, plan, i, reflection)
					if replanErr != nil {
						slog.Warn("replan failed", "error", replanErr)
						break
					}

					// Append new steps from the replan.
					plan.Steps = append(plan.Steps[:i+1], newPlan.Steps...)
				}
				continue
			}

			// Store result in work memory.
			workMemory[fmt.Sprintf("step_%d", step.Step)] = result.Result

			// Push step_complete event.
			ch <- AgentEvent{
				Type: "step_complete",
				Data: map[string]interface{}{
					"step":   step.Step,
					"result": result.Result,
					"retries": result.Retries,
				},
			}

			// Reflect on the result.
			reflection, evalErr := s.Evaluate(ctx, step, result)
			if evalErr != nil {
				slog.Warn("reflection error", "step", step.Step, "error", evalErr)
				continue
			}

			ch <- AgentEvent{Type: "reflection", Data: reflection}

			switch reflection.Status {
			case "failed":
				// Stop execution entirely.
				return
			case "replan":
				newPlan, replanErr := s.Replan(ctx, plan, i, reflection)
				if replanErr != nil {
					slog.Warn("replan failed", "error", replanErr)
					continue
				}
				// Replace remaining steps with replanned steps.
				plan.Steps = append(plan.Steps[:i+1], newPlan.Steps...)
			case "ok":
				// Continue to next step.
			}
		}

		// Generate summary from work memory.
		summary := s.generateSummary(ctx, plan, workMemory)
		if summary != "" {
			ch <- AgentEvent{
				Type: "summary",
				Data: map[string]interface{}{
					"content": summary,
				},
			}
		}

		// Push the [DONE] marker.
		ch <- AgentEvent{Type: "[DONE]", Data: nil}
	}()

	return ch, nil
}

// generateSummary calls the LLM to produce a natural language summary from
// all step results stored in the work memory.
func (s *AgentService) generateSummary(ctx context.Context, plan *AgentPlan, workMemory map[string]string) string {
	if len(workMemory) == 0 {
		return "任务执行完毕，但未获取到有效数据。"
	}

	// Build a summary of all steps from work memory.
	var stepSummaries []string
	for _, step := range plan.Steps {
		key := fmt.Sprintf("step_%d", step.Step)
		value, ok := workMemory[key]
		if !ok {
			continue
		}
		// Truncate long results.
		if len(value) > 500 {
			value = value[:500] + "..."
		}
		stepSummaries = append(stepSummaries, fmt.Sprintf(
			"Step %d (%s): %s", step.Step, step.Intent, value,
		))
	}

	if len(stepSummaries) == 0 {
		return "任务执行完毕。"
	}

	userContent := fmt.Sprintf(
		"Summarize these task execution results into a concise, professional natural-language response in Chinese. Keep it under 3 paragraphs. Do not use emoji.\n\nResults:\n%s",
		strings.Join(stepSummaries, "\n"),
	)

	messages := []openai.ChatCompletionMessage{
		{
			Role:    openai.ChatMessageRoleSystem,
			Content: "You are a steel industry assistant. Summarize task results concisely in Chinese. Be professional and factual.",
		},
		{Role: openai.ChatMessageRoleUser, Content: userContent},
	}

	resp, err := s.llmAdapter.Chat(ctx, messages)
	if err != nil || len(resp.Choices) == 0 {
		slog.Warn("summary generation failed", "error", err)
		return "任务执行完毕，请查看详细结果。"
	}

	return strings.TrimSpace(resp.Choices[0].Message.Content)
}

// ============================================================================
// Reflector Implementation (Task 4)
// ============================================================================

// Evaluate assesses the quality of a step result and returns a reflection
// indicating whether to continue, replan, or fail.
func (s *AgentService) Evaluate(
	ctx context.Context,
	step PlanStep,
	result *StepResult,
) (*ReflectionResult, error) {
	if result == nil {
		return &ReflectionResult{Status: "failed", Reason: "no result"}, nil
	}

	// If the step failed outright, it's a failure.
	if !result.Success {
		return &ReflectionResult{
			Status: "failed",
			Reason: result.Error,
		}, nil
	}

	// If the result is empty, ask to replan.
	if result.Result == "" {
		return &ReflectionResult{
			Status:     "replan",
			Reason:     "无数据",
			Suggestion: "尝试扩大搜索范围或调整查询条件",
		}, nil
	}

	// If the result contains signals of no data found, replan.
	noDataSignals := []string{"未查询到", "未找到", "暂无数据", "无相关", "not found", "no data"}
	for _, signal := range noDataSignals {
		if strings.Contains(strings.ToLower(result.Result), strings.ToLower(signal)) {
			return &ReflectionResult{
				Status:     "replan",
				Reason:     "无数据: " + signal,
				Suggestion: "尝试扩大搜索范围或调整查询条件",
			}, nil
		}
	}

	// If the result contains a "source" or "updated_at" field (valid data), it's OK.
	validitySignals := []string{`"source"`, `"updated_at"`, `"price"`, `"prices"`}
	resultLower := strings.ToLower(result.Result)
	for _, signal := range validitySignals {
		if strings.Contains(resultLower, signal) {
			return &ReflectionResult{Status: "ok"}, nil
		}
	}

	// For other cases, do a lightweight LLM check.
	return s.llmEvaluate(ctx, step, result)
}

// llmEvaluate uses a lightweight LLM call to check whether a step result
// is sufficient for the user's intent.
func (s *AgentService) llmEvaluate(
	ctx context.Context,
	step PlanStep,
	result *StepResult,
) (*ReflectionResult, error) {
	prompt := fmt.Sprintf(
		`Evaluate this step execution result.

Step intent: %s
Step result: %s

Is this result sufficient to satisfy the step intent? 
Respond with ONLY a JSON object: {"status": "ok"} or {"status": "replan", "reason": "...", "suggestion": "..."} or {"status": "failed", "reason": "..."}`,
		step.Intent,
		result.Result,
	)

	messages := []openai.ChatCompletionMessage{
		{Role: openai.ChatMessageRoleUser, Content: prompt},
	}

	resp, err := s.llmAdapter.Chat(ctx, messages)
	if err != nil {
		// If LLM evaluation fails, default to "ok" so execution continues.
		slog.Warn("LLM evaluation call failed, defaulting to ok", "error", err)
		return &ReflectionResult{Status: "ok"}, nil
	}

	if len(resp.Choices) == 0 || resp.Choices[0].Message.Content == "" {
		return &ReflectionResult{Status: "ok"}, nil
	}

	raw := strings.TrimSpace(resp.Choices[0].Message.Content)
	// Strip markdown fences.
	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	var reflection ReflectionResult
	if err := json.Unmarshal([]byte(raw), &reflection); err != nil {
		slog.Warn("LLM evaluation returned invalid JSON, defaulting to ok",
			"raw", raw,
			"error", err,
		)
		return &ReflectionResult{Status: "ok"}, nil
	}

	// Normalize status.
	switch reflection.Status {
	case "ok", "replan", "failed":
		// Valid.
	default:
		reflection.Status = "ok"
	}

	return &reflection, nil
}

// evaluateFailure creates a reflection result for a failed step without
// calling the LLM.
func (s *AgentService) evaluateFailure(step PlanStep, result *StepResult) *ReflectionResult {
	errMsg := "unknown error"
	if result != nil {
		errMsg = result.Error
	}
	return &ReflectionResult{
		Status: "replan",
		Reason: fmt.Sprintf("Step %d failed: %s", step.Step, errMsg),
	}
}

// Replan adjusts the remaining steps of a plan based on reflection feedback.
func (s *AgentService) Replan(
	ctx context.Context,
	originalPlan *AgentPlan,
	currentStepIndex int,
	reflection *ReflectionResult,
) (*AgentPlan, error) {
	if currentStepIndex < 0 || currentStepIndex >= len(originalPlan.Steps) {
		return &AgentPlan{
			Steps:     nil,
			MaxSteps:  originalPlan.MaxSteps,
			CreatedAt: time.Now(),
		}, nil
	}

	// Get the remaining steps (after currentStepIndex).
	remainingSteps := originalPlan.Steps[currentStepIndex+1:]
	if len(remainingSteps) == 0 {
		return &AgentPlan{
			Steps:     nil,
			MaxSteps:  originalPlan.MaxSteps,
			CreatedAt: time.Now(),
		}, nil
	}

	// Serialize the remaining steps for the LLM.
	remainingJSON, _ := json.Marshal(remainingSteps)

	prompt := fmt.Sprintf(
		`Step %d failed or needs adjustment. 

Failure reason: %s
Suggestion: %s

Remaining steps:
%s

Adjust the remaining steps to account for this failure. Remove unnecessary steps, add new ones if needed, and renumber them starting from step %d.

Return ONLY a JSON array of adjusted steps.`,
		originalPlan.Steps[currentStepIndex].Step,
		reflection.Reason,
		reflection.Suggestion,
		string(remainingJSON),
		originalPlan.Steps[currentStepIndex].Step+1,
	)

	messages := []openai.ChatCompletionMessage{
		{
			Role:    openai.ChatMessageRoleSystem,
			Content: "You are a task replanner. Adjust remaining execution steps based on feedback. Return ONLY a valid JSON array of step objects.",
		},
		{Role: openai.ChatMessageRoleUser, Content: prompt},
	}

	resp, err := s.llmAdapter.Chat(ctx, messages)
	if err != nil {
		slog.Warn("replan LLM call failed", "error", err)
		return &AgentPlan{Steps: nil, MaxSteps: originalPlan.MaxSteps, CreatedAt: time.Now()}, nil
	}

	if len(resp.Choices) == 0 || resp.Choices[0].Message.Content == "" {
		return &AgentPlan{Steps: nil, MaxSteps: originalPlan.MaxSteps, CreatedAt: time.Now()}, nil
	}

	raw := strings.TrimSpace(resp.Choices[0].Message.Content)
	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	// Parse as either a single-step object or an array.
	var newSteps []PlanStep
	if err := json.Unmarshal([]byte(raw), &newSteps); err != nil {
		// Try parsing as a single object.
		var single PlanStep
		if err2 := json.Unmarshal([]byte(raw), &single); err2 != nil {
			slog.Warn("replan returned invalid JSON, dropping remaining steps",
				"raw", raw,
				"error", err,
			)
			return &AgentPlan{Steps: nil, MaxSteps: originalPlan.MaxSteps, CreatedAt: time.Now()}, nil
		}
		newSteps = []PlanStep{single}
	}

	// Enforce max steps.
	if len(newSteps) > originalPlan.MaxSteps {
		newSteps = newSteps[:originalPlan.MaxSteps]
	}

	return &AgentPlan{
		Steps:     newSteps,
		MaxSteps:  originalPlan.MaxSteps,
		CreatedAt: time.Now(),
	}, nil
}

// ============================================================================
// Memory Maintenance (Task 7.3)
// ============================================================================

// CleanExpiredMemories deletes long-term memory entries that have not been
// accessed within the past 30 days. Returns the number of deleted records.
// This method is intended to be called periodically (e.g. via a scheduled
// task or cron job) to prevent the memories table from growing unbounded.
func (s *AgentService) CleanExpiredMemories(ctx context.Context) (int64, error) {
	return s.memoryRepo.DeleteExpired(ctx, 30*24*time.Hour)
}

// CleanExpiredEmbeddings deletes semantic memory embedding records older than
// 90 days. Returns the number of deleted records. This method is intended to be
// called periodically to prevent the embeddings table from growing unbounded.
func (s *AgentService) CleanExpiredEmbeddings(ctx context.Context) (int64, error) {
	if s.vectorRepo == nil {
		return 0, nil
	}
	return s.vectorRepo.DeleteExpired(ctx, 90*24*time.Hour)
}
